# -*- coding: utf-8 -*-
"""Lab5_part_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sYOogsoOgGdNrJP0_jaWJQdXAQOS4YZo
"""

!wget -q -nc https://raw.githubusercontent.com/pseprivamirakbarnejad/cmput206lab/master/Lab5/lab5_img.jpeg
!ls

# Import libraries
import numpy as np 
from skimage import io, exposure, img_as_ubyte
import matplotlib.pyplot as plt
from skimage.filters import rank
from skimage.morphology import disk

img = io.imread('lab5_img.jpeg')  

T_r = np.array([
    [0, 1, 0], 
    [-1,  0, 0], 
    [0, 0, 1]
])

T_s = np.array([
    [2, 0, 0], 
    [0, 2, 0], 
    [0, 0, 1]
])

T = T_s @ T_r

print(T)

#for x in range(1, img.shape[0] - 1):
#    for y in range(1, img.shape[1] - 1):
#        img = T * img[(x - 1):(x + 2), (y - 1):(y + 2)]






plt.imshow(img,cmap='gray')
plt.show()