# -*- coding: utf-8 -*-
"""Lab2_part_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BzPg-Z8SE8wYJTKTAWIymSLraeUtPRfg
"""

!wget -q -nc https://raw.githubusercontent.com/pseprivamirakbarnejad/cmput206lab/master/Lab2/noisy.jpg
!ls

import numpy as np 
from skimage import io, exposure, img_as_ubyte, filters
import matplotlib.pyplot as plt

img = io.imread('noisy.jpg')

median = filters.median(img)
gaussian = filters.gaussian(img)

print("Original Image Below:")
plt.imshow(img, cmap="gray")
plt.show()
print("Median Filtered Image Below:")
plt.imshow(median, cmap="gray")
plt.show()
print("Gaussian Filtered Image Below:")
plt.imshow(gaussian, cmap="gray")
plt.show()



"""**The Median filtered image was much more successful.**"""